springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    csrf:
      enabled: true
    disable-swagger-default-url: true
  packages-to-scan: com.developersboard.web.rest.v1

openapi:
  version: ${API_VERSION:1.0.0}
  name: ${API_NAME:${system.name}}
  description: ${API_DESCRIPTION:B2C Transaction API Mock for KCB}

africastalking:
  username: "00000"
  apikey: "0000000"
  from: "254791179389" # optional, if you have a shortcode or registered phone number

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        query:
          plan_cache_max_size: 4096
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
      hypersistence:
        query:
          max_result_size: 50
        session:
          timeout_millis: 1000
          flush_timeout_millis: 1000
  activemq:
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 200
      idle-timeout: 30
      max-sessions-per-connection: 500
      block-if-full: false
      time-between-expiration-check: 100
    #broker-url: tcp://localhost:61616
    broker-url:  http://localhost:8161/admin
    user: admin
    password: admin